### ISSUE TITLE
possible missing depends for pthread on CMakeLists.txt

### ISSUE THREAD

**Issue by ftoledo** [madpuppet/Mad64#1]
I try to build on debian 11.
sems to missing pthread library on cmake

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")

ref: https://stackoverflow.com/questions/34143265/undefined-reference-to-symbol-pthread-createglibc-2-2-5

´´´
ragnarok@ragnarok:/tmp/tt/Mad64/build$ cmake ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tt/Mad64/build
ragnarok@ragnarok:/tmp/tt/Mad64/build$ make
[  6%] Building CXX object CMakeFiles/Mad64.dir/source/application.cpp.o
[ 12%] Building CXX object CMakeFiles/Mad64.dir/source/appSettings.cpp.o
[ 18%] Building CXX object CMakeFiles/Mad64.dir/source/cmdManager.cpp.o
[ 25%] Building CXX object CMakeFiles/Mad64.dir/source/compiler.cpp.o
[ 31%] Building CXX object CMakeFiles/Mad64.dir/source/contextualHelp.cpp.o
[ 37%] Building CXX object CMakeFiles/Mad64.dir/source/editWindow.cpp.o
[ 43%] Building CXX object CMakeFiles/Mad64.dir/source/graphicChunk.cpp.o
[ 50%] Building CXX object CMakeFiles/Mad64.dir/source/logWindow.cpp.o
[ 56%] Building CXX object CMakeFiles/Mad64.dir/source/main.cpp.o
[ 62%] Building CXX object CMakeFiles/Mad64.dir/source/sourcefile.cpp.o
[ 68%] Building CXX object CMakeFiles/Mad64.dir/source/textInput.cpp.o
[ 75%] Building CXX object CMakeFiles/Mad64.dir/source/thread.cpp.o
[ 81%] Building CXX object CMakeFiles/Mad64.dir/source/c64ram.cpp.o
[ 87%] Building CXX object CMakeFiles/Mad64.dir/source/emulator.cpp.o
[ 93%] Building C object CMakeFiles/Mad64.dir/source/tinyfiledialogs.c.o
[100%] Linking CXX executable Mad64
/usr/bin/ld: CMakeFiles/Mad64.dir/source/thread.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error al añadir símbolos: DSO faltante desde línea de orden
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Mad64.dir/build.make:321: Mad64] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Mad64.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

´´´

**Comment by ftoledo** [comment]
can missing SDL includes too?:

´´´
ragnarok@ragnarok:/tmp/tt/Mad64/build$ make
Consolidate compiler generated dependencies of target Mad64
[  6%] Linking CXX executable Mad64
/usr/bin/ld: CMakeFiles/Mad64.dir/source/application.cpp.o: en la función `Application::Application()':
application.cpp:(.text+0x296): referencia a `SDL_RenderSetVSync' sin definir
/usr/bin/ld: CMakeFiles/Mad64.dir/source/application.cpp.o: en la función `Application::HandleEvent(SDL_Event*)':
application.cpp:(.text+0x935): referencia a `SDL_GetTicks64' sin definir
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Mad64.dir/build.make:321: Mad64] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Mad64.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

´´´

**Comment by madpuppet** [comment]
I'll have to set up a debian virtual machine to test it out.  I didn't have to do any of that for ubuntu, so no idea.

**Comment by madpuppet** [comment]
Fixed now.   seems debian only has SDL2 10.0.4   but some functions were in 10.0.8.
