### ISSUE TITLE
macOS builds

### ISSUE THREAD

**Issue by ChristianWeyer** [madpuppet/Mad64#2]
Hey - what a fantastic project :-)

I am on an M1 ARM Mac. I am happy to help if you want to build this also for macOS (at least for ARM).
In one of the Facebook groups, you said you have someone who already did that...?

Should we add instructions here?

Thanks,
Christian

**Comment by madpuppet** [comment]
That would be awesome!  Thanks.

 

It’s using SDL2 and CMAKE so the linux build notes should get you close if you know much about cmake?

 

I’m on discord if you wanna chat sometime

 

madpuppet#0387

 

I have a friend with a mac that has got it working but he’s been to busy to help out further, and I haven’t even been able to get more info from him yet on what he needed to do to get it going.

 

 

 

From: Christian Weyer ***@***.***> 
Sent: 18 November 2022 00:13
To: madpuppet/Mad64 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [madpuppet/Mad64] macOS builds (Issue #2)

 

Hey - what a fantastic project :-)

I am on an M1 ARM Mac. I am happy to help if you want to build this also for macOS (at least for ARM).
In one of the Facebook groups, you said you have someone who already did that...?

Should we add instructions here?

Thanks,
Christian

**Comment by ChristianWeyer** [comment]
Cool. Let's try this together.
On which Discord are you?

**Comment by ChristianWeyer** [comment]
I installed the XCode command line tools, cmake, and SDL2.

And already run into an error 🤪:

```
➜  Mad64 git:(main) cmake --build build --config release
[  4%] Linking CXX executable Mad64
ld: library not found for -lSDL2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Mad64] Error 1
make[1]: *** [CMakeFiles/Mad64.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ChristianWeyer** [comment]
OK, one step further: I can compile it now.
But when starting, I get a segmentation fault.

**Comment by madpuppet** [comment]
I assume you are on latest pull?  I did have an issue a little while ago with it crashing the very first time you run because there is no settings file yet.

The second attempt to run would work.

Though that should be fixed now.

**Comment by madpuppet** [comment]
I’ve create a server

 

https://discord.gg/rcKYTGMu

**Comment by madpuppet** [comment]
I’m in Australia so our timezone overlap will be choppy 😊  but I’m online pretty much all day every day.

 

 

From: ***@***.*** ***@***.***> 
Sent: 18 November 2022 09:05
To: 'madpuppet/Mad64' ***@***.***>; 'madpuppet/Mad64' ***@***.***>
Cc: 'Comment' ***@***.***>
Subject: RE: [madpuppet/Mad64] macOS builds (Issue #2)

 

I’ve create a server

 

https://discord.gg/rcKYTGMu

**Comment by madpuppet** [comment]
heh. I didn't know github automatically put all these emails on the issues database.

**Comment by madpuppet** [comment]
We can move this conversation straight to the github issue,  or chat about it on discord.

**Comment by madpuppet** [comment]
can you post your "log.txt" file... might be some clue there.  I might need to add more logging to see where its crashing.

**Comment by madpuppet** [comment]
hey, I have another user that has done a fix for the segmentation fault issue. He should be submitting a pull request on the weekend.

**Comment by ChristianWeyer** [comment]
> can you post your "log.txt" file... might be some clue there. I might need to add more logging to see where its crashing.

I don't think this helps 😉:

```
Load Settings file: /Users/christianweyer/Library/Application Support/madpuppet/mad64/settings.ini
Create Font: font.ttf

```
