### ISSUE TITLE
Different MacOS Build Issue

### ISSUE THREAD

**Issue by anthonyjclarke** [madpuppet/Mad64#4]
Echo previous comments, amazing project! Trying to build.... completes all well and previous steps until I get to the following step:

cmake --build build --config release

Output is then as follows:

[  4%] Building CXX object CMakeFiles/Mad64.dir/source/application.cpp.o
In file included from /Users/ant/Mad64/source/application.cpp:1:
In file included from /Users/ant/Mad64/source/common.h:129:
In file included from /Users/ant/Mad64/source/application.h:6:
In file included from /Users/ant/Mad64/source/compiler.h:3:
/Users/ant/Mad64/source/contextualHelp.h:21:13: error: definition of variable with array type needs an explicit size or an initializer
const char* gHELP_CIA1_DATAPORTA[];
            ^
/Users/ant/Mad64/source/contextualHelp.h:22:13: error: definition of variable with array type needs an explicit size or an initializer
const char* gHELP_CIA1_DATAPORTB[];
            ^
/Users/ant/Mad64/source/contextualHelp.h:23:13: error: definition of variable with array type needs an explicit size or an initializer
const char* gHELP_CIA1_INTCONTROL[];
            ^
/Users/ant/Mad64/source/contextualHelp.h:24:13: error: definition of variable with array type needs an explicit size or an initializer
const char* gHELP_CIA1_CONTROLTIMERA[];
            ^
/Users/ant/Mad64/source/contextualHelp.h:25:13: error: definition of variable with array type needs an explicit size or an initializer
const char* gHELP_CIA1_CONTROLTIMERB[];
            ^
5 errors generated.
make[2]: *** [CMakeFiles/Mad64.dir/source/application.cpp.o] Error 1
make[1]: *** [CMakeFiles/Mad64.dir/all] Error 2
make: *** [all] Error 2

Really appreciate it if you have any suggestions.  Thank you

PS build an Ubuntu VM in Parallels and got stuck at the same place

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/9491428/206887568-f9f03383-1e58-4db8-a049-63b7436d47ae.png">

**Comment by madpuppet** [comment]
fixed now.  tested on ubuntu.
Note that the I'm reworking the log windows to use a new dockable system with support for misc icons in the title bar for stuff like filtering contents,  so some things like the emulation window and memory dump will be down for a day or so.

**Comment by anthonyjclarke** [comment]
All working now for both Mac and Ubuntu.... BTW had to re-install SDL and SDL TTF again to get it to work...

**Comment by madpuppet** [comment]
cool, though strange.  I rebuilt on ubuntu but only had to delete my build folder and remake with cmake.
still doing major refactoring though,  so some of the older features like search & replace and Memory View are not working again yet.  Refactor should be finished by the end of the week and allows all the debug windows to be undockable,  and a more consistent use of scroll bars for editwindow / dockable windows / undocked windows.
